### ISSUE TITLE
no .mobi files in the download

### ISSUE THREAD

**Issue by susadu** [jrfonseca/jmdict-kindle#10]
do I need a program to open the files in the zip drive in order to find the .mobi dictionary files?

**Comment by thomshutt** [comment]
Adding to this, would it be possible to have the files (unzipped) as part of the release? I didn't have a laptop and was trying to download using just my Kindle recently

**Comment by jrfonseca** [comment]
Yes, the downloads are currently compressed into a 7-zip archive to save space/bandwidth.  One can get utility to unpack from https://www.7-zip.org/

If they weren't packed in 7-zip format, their total size would be 2x larger. On the other hand, one could just download individual dictionary files instead of all three.  I'll look into it for the next release.

**Comment by jrfonseca** [comment]
Fixed.  See https://github.com/jrfonseca/jmdict-kindle/releases/tag/2.0.20210221

**Comment by thomshutt** [comment]
That's awesome, thanks @jrfonseca!
