### ISSUE TITLE
Does Jmdict work properly on IOS kindle app?

### ISSUE THREAD

**Issue by mihai-morman** [jrfonseca/jmdict-kindle#15]
Hello,

I am a heavy user of your dictionary on kindle e-ink and i am thinking of getting a tablet, so i want to know if this part is also True for IOS kindle app. 

"NOTE: Unfortunately the Kindle Android App does not support dictionary inflections, yielding verbs lookup practically impossible. No known workaround."

Thank you for the dictionary, awesome work!

**Comment by jrfonseca** [comment]
Hi.  Thanks for the feedback!

I never tried the iOS Kindle app myself, or got direct reports of inflection working or not working on iOS Kindle app.

I googled around, but I found mixed reports:
- [this](https://www.reddit.com/r/LearnJapanese/comments/e4zkf8/kindle_android_dictionary_doesnt_support/) implies it's supported
- [this](https://community.wanikani.com/t/a-good-reader-device-to-read-japanese-stuff/48907/16) implies it's not..!

If this is a show-stopper for you, then I'd recommend asking a friend with iPad/iPhone to give it a try.  If you're buying new online, then in most countries one can return purchases free of charge if it doesn't meet your needs, provided you keep the device and packaging in original condition.

Let me know if you ever found the answer!

**Comment by quanticism** [comment]
I couldn't get inflection lookup to work with both the default JE and JJ dictionaries. I purchased another [JE dictionary](https://www.amazon.com/Japanese-English-Dictionary-Thomas-McCarthy-ebook/dp/B00ESCGQS6/ref=sr_1_3?dchild=1&keywords=japanese+english+dictionary+kindle&qid=1626172448&s=digital-text&sr=1-3) since some comments said it was able to lookup inflected words (presumably on Paperwhite) but that also failed to lookup words like `許される` and `包んだ`.

I'm not sure how to try Jmdict on iOS (i.e. what file browser program to use to manually replace which dictionary file in iOS's file system) but given how the dictionary I purchased failed, I'd wager that Jmdict also won't work...

**Comment by jrfonseca** [comment]
Thanks for letting us know, @quanticism .

Regarding getting Kindle iOS app to accept the JMDict Kindle dictionary, I found [this guide](https://learnoutlive.com/add-german-english-dictionary-to-kindle-on-your-ipad-or-iphone-ios/).  But from you described I wouldn't expect different results.  Probably Amazon only implemented inflection on Kindle.

I'll update the README to reflect this.

**Comment by xelloss1012** [comment]
Hello!,

I had the same problem and, after struggling with this issue, I finally have been able to solve my problem by building a workaround version that saves inflections as alternate indexes, so the app can at least find the main word when searching for an inflected word. 

I have this version on my [releases page](https://github.com/xelloss1012/jmdict-kindle/releases) so anyone can download it. Take into account that it has been just tested in the Android app though, but I think it should work also in iOS or another platforms.

**Note:** I have submitted a Pull Request (#25) so it to be added to the main project.
